apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
    # - protocol: TCP
    #   port: 443
    #   targetPort: 7070
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector: # Pod를 선택하는 방법을 정의
    matchLabels:
      app: second-app
      tier: backend
  template: 
    metadata:
      labels:
        # Pod의 label을 정의, key-value 형태로 정의되며 값은 사용자가 정의, selector와 매칭되어야 함
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: eunhomoon/kub-first-app:2.1