services:
  mysql:
    image: mysql:8.0
    container_name: mysql_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3406:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
