version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    environment:
      AUTH_API_URL: auth
      AUTH_SERVICE_SERVICE_HOST: auth
    ports:
      - "5080:8080"
  tasks:
    build: ./tasks-api
    ports:
      - "5000:8000"
    environment:
      TASKS_FOLDER: tasks
      AUTH_API_URL: auth
      AUTH_SERVICE_SERVICE_HOST: auth
