apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: eunhomoon/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.106.43.225"
              value: "auth-service.default"